import { fileURLToPath, URL } from 'node:url'
import tailwindcss from '@tailwindcss/vite'
import react from '@vitejs/plugin-react'
import { coverageConfigDefaults, defineConfig } from 'vitest/config'

export default defineConfig({
  plugins: [react(), tailwindcss()],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: ['./vitest.setup.ts'],
    css: true,
    coverage: {
      provider: 'v8',
      reporter: ['text', 'text-summary'],
      // Without this a failing run prints no report at all, which makes
      // "which file dropped?" needlessly hard to answer in CI.
      reportOnFailure: true,
      include: ['src/**/*.{ts,tsx}'],
      exclude: [
        // `exclude` REPLACES the defaults rather than merging with them. Drop
        // this spread and colocated `*.test.tsx` files start counting as
        // source, inflating every metric toward ~99% and turning the gate
        // below into a rubber stamp.
        ...coverageConfigDefaults.exclude,
        // Coverage reports every file matched by `include`, even ones no test
        // imports. These have no branches worth asserting and would only drag
        // the global bucket down.
        'src/main.tsx',
        'src/vite-env.d.ts',
        // Bootstrap only: composes providers around a router. The route table
        // it renders lives in `app/routes.tsx`, which *is* covered — tests
        // mount it through a memory router and navigate for real.
        'src/app/app.tsx',
        // The default excludes only match a root-level `test-utils`, not a
        // nested one, so this has to be listed explicitly.
        'src/test/**',
        // Generated by graphql-codegen from `schema.graphql`. Asserting on
        // generated output tests the generator, not this project.
        'src/graphql/generated/**',
        // MSW's browser entrypoint runs only in the dev server, never in jsdom.
        'src/mocks/browser.ts',
      ],
      thresholds: {
        statements: 85,
        branches: 85,
        functions: 85,
        lines: 85,
      },
    },
  },
})
